import http from 'node:http';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import Busboy from 'busboy';
import { getMedia, getPost, initDatabase, listPosts, mediaBucket, removePost, saveMedia, savePost } from './lib/database.mjs';

const root = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(root, 'public');
const port = Number(process.env.PORT || 4173);
const password = process.env.ADMIN_PASSWORD;
const sessions = new Map();
const secureCookie = process.env.NODE_ENV === 'production' ? '; Secure' : '';
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
const allowedTags = new Set(['p','br','strong','b','em','i','u','h2','h3','blockquote','ul','ol','li','a','code','pre','hr','img']);
const imageTypes = new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp'],['image/gif','gif']]);
const audioTypes = new Map([['audio/mpeg','mp3'],['audio/mp3','mp3'],['audio/ogg','ogg'],['audio/wav','wav']]);

const send = (res,status,payload,headers={}) => res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers}).end(JSON.stringify(payload));
const cookie = req => req.headers.cookie?.match(/jing_session=([^;]+)/)?.[1];
const clean = (value,limit) => String(value ?? '').trim().slice(0,limit);
const escapeAttribute = value => String(value).replace(/[&<>"']/g,char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const attribute = (source,name) => source.match(new RegExp(`\\b${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'=<>]+))`,'i'))?.slice(1).find(value => value !== undefined) || '';

function isAdmin(req) { const token=cookie(req), expiresAt=sessions.get(token); if (!expiresAt || expiresAt<=Date.now()) { sessions.delete(token); return false; } return true; }
function safeHref(raw) { const value=String(raw || '').trim(); if (!value || value.startsWith('#') || value.startsWith('/')) return value; try { const url=new URL(value); return ['http:','https:','mailto:'].includes(url.protocol) ? value : ''; } catch { return ''; } }
function safeMediaPath(value) { return /^\/media\/[0-9a-f-]{36}$/i.test(value) ? value : ''; }
function plainText(value) { return String(value ?? '').replace(/<\s*br\s*\/?>/gi,' ').replace(/<\/(p|h2|h3|li|blockquote|pre)>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim(); }
function sanitizeHtml(value) { const forbidden='script|style|iframe|object|embed|svg|math|form|input|button|textarea|select'; return String(value ?? '').slice(0,30000).replace(new RegExp(`<\\s*(${forbidden})\\b[^>]*>[\\s\\S]*?<\\s*\\/\\s*\\1\\s*>`,'gi'),'').replace(/<!--[\s\S]*?-->/g,'').replace(/<\s*(\/?)\s*([a-z0-9]+)([^>]*)>/gi,(_,closing,name,attributes) => { const tag=name.toLowerCase(); if (!allowedTags.has(tag)) return ''; if (closing) return tag === 'img' ? '' : `</${tag}>`; if (tag === 'img') { const src=safeMediaPath(attribute(attributes,'src')); const alt=clean(attribute(attributes,'alt'),180); return src ? `<img src="${src}" alt="${escapeAttribute(alt)}" loading="lazy">` : ''; } if (tag !== 'a') return `<${tag}>`; const href=safeHref(attribute(attributes,'href')); return href ? `<a href="${escapeAttribute(href)}" rel="noopener noreferrer">` : '<a>'; }).trim(); }
function postFrom(input,old={}) { const title=clean(input.title,160), contentFormat=input.contentFormat === 'html' ? 'html' : 'text', content=contentFormat === 'html' ? sanitizeHtml(input.content) : clean(input.content,30000); if (!title || !plainText(content)) throw Error('标题和正文不能为空'); const text=plainText(content); return {id:old.id || crypto.randomUUID(),title,category:clean(input.category,30) || '未分类',date:/^\d{4}-\d{2}-\d{2}$/.test(input.date) ? input.date : new Date().toISOString().slice(0,10),excerpt:clean(input.excerpt,260) || text.slice(0,90),content,contentFormat,backgroundMusicId:clean(input.backgroundMusicId,36) || null,published:input.published !== false}; }
const body = req => new Promise((resolve,reject) => { let raw=''; req.on('data',chunk => { raw += chunk; if (raw.length>1e6) reject(Error('请求内容过大')); }); req.on('end',() => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(Error('无效 JSON')); } }); req.on('error',reject); });

async function verifyBackgroundMusic(id) { if (!id) return; const media=await getMedia(id); if (!media || media.kind !== 'audio') throw Error('所选配乐不存在或不是音频文件'); }
function receiveUpload(req) { return new Promise((resolve,reject) => { let fields={}, uploaded=false, settled=false, pending, result; const fail=error => { if (!settled) { settled=true; reject(error); } }; const busboy=Busboy({headers:req.headers,limits:{files:1,fileSize:20*1024*1024,fields:4}}); busboy.on('field',(name,value) => { fields[name]=value; }); busboy.on('file',(field,file,info) => { if (uploaded) { file.resume(); return fail(Error('一次只能上传一个文件')); } uploaded=true; const kind=fields.kind, types=kind === 'image' ? imageTypes : kind === 'audio' ? audioTypes : null, extension=types?.get(info.mimeType); if (field !== 'file' || !extension) { file.resume(); return fail(Error(kind ? '不支持的文件格式' : '缺少媒体类型')); } const maxBytes=kind === 'image' ? 8*1024*1024 : 20*1024*1024; const id=crypto.randomUUID(), objectName=`media/${kind}/${id}.${extension}`, target=mediaBucket().file(objectName), output=target.createWriteStream({resumable:false,metadata:{contentType:info.mimeType,cacheControl:'public, max-age=31536000, immutable'}}); let byteSize=0, limited=false; file.on('data',chunk => { byteSize += chunk.length; result.byteSize=byteSize; }); file.on('limit',() => { limited=true; output.destroy(Error(`文件不能超过 ${Math.round(maxBytes / 1024 / 1024)}MB`)); }); pending=new Promise((done,failed) => { output.on('finish',done); output.on('error',failed); }); file.pipe(output); result={id,kind,objectName,originalName:clean(info.filename || 'upload',255),contentType:info.mimeType,byteSize,bucket:target,limited,maxBytes}; }); busboy.on('error',fail); busboy.on('finish',async () => { if (settled) return; if (!uploaded || !pending) return fail(Error('请选择一个文件')); try { await pending; if (result.limited || result.byteSize > result.maxBytes) return fail(Error(`文件不能超过 ${Math.round(result.maxBytes / 1024 / 1024)}MB`)); settled=true; resolve(result); } catch (error) { fail(error); } }); req.pipe(busboy); }); }
async function serveMedia(res,id) { const media=await getMedia(id); if (!media) return res.writeHead(404).end('Not found'); const stream=mediaBucket().file(media.objectName).createReadStream(); stream.once('error',() => { if (!res.headersSent) res.writeHead(404).end('Not found'); else res.destroy(); }); res.writeHead(200,{'Content-Type':media.contentType,'Content-Length':media.byteSize,'Cache-Control':'public, max-age=31536000, immutable','Content-Disposition':'inline'}); stream.pipe(res); }

async function api(req,res,pathname) { try { const admin=isAdmin(req), postMatch=pathname.match(/^\/api\/posts\/([^/]+)$/), mediaMatch=pathname.match(/^\/api\/media\/([^/]+)$/); if (req.method === 'GET' && pathname === '/api/posts') return send(res,200,await listPosts(admin)); if (req.method === 'GET' && postMatch) { const post=await getPost(postMatch[1]); return !post || (!post.published && !admin) ? send(res,404,{error:'文章不存在'}) : send(res,200,post); } if (req.method === 'GET' && mediaMatch) { const media=await getMedia(mediaMatch[1]); return media ? send(res,200,media) : send(res,404,{error:'媒体不存在'}); } if (req.method === 'GET' && pathname === '/api/me') return send(res,200,{authenticated:admin,configured:Boolean(password)}); if (req.method === 'POST' && pathname === '/api/login') { if (!password) return send(res,503,{error:'服务器尚未设置 ADMIN_PASSWORD'}); const input=await body(req), supplied=Buffer.from(clean(input.password,256).padEnd(256)), expected=Buffer.from(password.slice(0,256).padEnd(256)); if (!crypto.timingSafeEqual(supplied,expected)) return send(res,401,{error:'密码不正确'}); const token=crypto.randomBytes(32).toString('hex'); sessions.set(token,Date.now()+864e5); return send(res,200,{ok:true},{'Set-Cookie':`jing_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${secureCookie}`}); } if (req.method === 'POST' && pathname === '/api/logout') { sessions.delete(cookie(req)); return send(res,200,{ok:true},{'Set-Cookie':`jing_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secureCookie}`}); } if (!admin) return send(res,401,{error:'请先登录'}); if (req.method === 'POST' && pathname === '/api/media') { const upload=await receiveUpload(req); try { return send(res,201,await saveMedia(upload)); } catch (error) { await upload.bucket.delete({ignoreNotFound:true}); throw error; } } if (req.method === 'POST' && pathname === '/api/posts') { const post=postFrom(await body(req)); await verifyBackgroundMusic(post.backgroundMusicId); return send(res,201,await savePost(post)); } if (req.method === 'PUT' && postMatch) { const old=await getPost(postMatch[1]); if (!old) return send(res,404,{error:'文章不存在'}); const post=postFrom(await body(req),old); await verifyBackgroundMusic(post.backgroundMusicId); return send(res,200,await savePost(post,true)); } if (req.method === 'DELETE' && postMatch) return await removePost(postMatch[1]) ? send(res,200,{ok:true}) : send(res,404,{error:'文章不存在'}); return send(res,404,{error:'接口不存在'}); } catch (error) { return send(res,400,{error:error.message || '请求失败'}); } }

const server=http.createServer(async (req,res) => { const pathname=new URL(req.url,`http://${req.headers.host}`).pathname; if (pathname.startsWith('/api/')) return api(req,res,pathname); const mediaMatch=pathname.match(/^\/media\/([^/]+)$/); if (mediaMatch) { try { return await serveMedia(res,mediaMatch[1]); } catch { return res.writeHead(404).end('Not found'); } } const file=pathname === '/' ? 'index.html' : pathname.slice(1), target=path.resolve(publicDir,file); if (!target.startsWith(publicDir)) return res.writeHead(403).end(); try { const data=await fs.readFile(target); res.writeHead(200,{'Content-Type':mime[path.extname(target)] || 'application/octet-stream','Cache-Control':'no-store'}).end(data); } catch { res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'}).end('Not found'); } });
initDatabase().then(() => server.listen(port,'127.0.0.1',() => console.log(`jing.lv is running at http://127.0.0.1:${port}`))).catch(error => { console.error(`数据库初始化失败：${error.message}`); process.exitCode=1; });
